### PR TITLE
Cleaned up core.py to pass circleci linting test

### PR DESCRIPTION
**Pull request by mnlevy1981**
flake8 was balking at an extra newline in the code, and after fixing that black
wanted to reformat a few calls with multiple arguments.

### CODE REVIEW

**Comment by mnlevy1981** [comment]
On the plus side, the `liniting` test is passing now! (I think there must be an upstream package change somewhere -- #9 passed the python tests but that was 4 months ago)

**Comment by andersy005** [comment]
There was a new release of xesmf a few weeks ago, and I suspect some of the issues to be coming from xesmf (not 💯sure) . Looking at the CI logs, the issue seems to be related to NumPy's assertion though.

**Comment by mnlevy1981** [comment]
@andersy005 it was indeed xesmf -- d602b1f is a band-aid (rolling back to the older xesmf), but figuring out the [new API to `apply_weights()`](https://github.com/JiaweiZhuang/xESMF/compare/v0.1.1..v0.2.0#diff-a89bc4a53c8f19e6090238f48870655fL44) would be a better path forward in my opinion

**Review by andersy005 — APPROVED** [review]
Thank you for looking into this and fixing the issue, @mnlevy1981! We can fix the xesmf issue in a separate PR.

**Pull request merged**
